name:        trade-journal
version:     0.0.2
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Command-line reporting utility for processing trade journals.

ghc-options:
   - -Wall
   - -Wno-missing-home-modules

dependencies:
  - aeson
  - base >= 4.5 && < 5.0
  - bytestring
  - cassava
  - containers
  - free
  - lens
  - megaparsec
  - mtl
  - pretty-show
  - simple-amount
  - tardis
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - Journal.Closings
    - Journal.Parse
    - Journal.Pipes
    - Journal.Print
    - Journal.Split
    - Journal.Types
    - Journal.Utils
    - Journal.Zippered
    - Broker.ThinkOrSwim
    - Taxes.USA.WashSaleRule
  dependencies:
    - data-default
    - pretty
    - profunctors
    - split
    - vector

tests:
  journal-tests:
    main: Main.hs
    source-dirs: tests/Journal
    dependencies:
      - HUnit
      - hedgehog
      - here
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - trade-journal

  thinkorswim-tests:
    main: Main.hs
    source-dirs: tests/Broker/ThinkOrSwim
    dependencies:
      - HUnit
      - hedgehog
      - here
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - trade-journal

executables:
  trade-journal:
    main: bin/Main.hs
    other-modules:
      - Options
    dependencies:
      - trade-journal
      - optparse-applicative
