name:       trade-journal
version:    1.0.0
license:    BSD3
author:     John Wiegley
maintainer: johnw@newartisans.com

ghc-options:
  - -Wall
  # - -Werror
  - -debug
  - -g3
  - -fno-ignore-asserts

dependencies:
  - aeson
  - base
  - bytestring
  - cassava
  - containers
  - lens
  - megaparsec
  - mtl
  - pretty-show
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src
  c-sources:
    - src/Journal/mpfr_printf.c
  extra-libraries:
    - mpfr
    - gmp
  exposed-modules:
    - Journal.Amount
    - Journal.Model
    - Journal.Parse
    - Journal.Split
    - Journal.ThinkOrSwim
    - Journal.Types
    - Journal.Utils
  dependencies:
    - data-default
    - pretty
    - profunctors
    - split
    - vector

tests:
  trade-journal-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - trade-journal
      - HUnit
      - hedgehog
      - here
      - tasty
      - tasty-hedgehog
      - tasty-hunit

executables:
  trade-journal:
    main: Main.hs
    other-modules:
      - Options
    dependencies:
      - trade-journal
      - optparse-applicative
