name:        trade-journal
version:     0.0.2
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Command-line reporting utility for processing trade journals.

ghc-options:
   - -Wall
   - -Wno-missing-home-modules

dependencies:
  - aeson
  - base >= 4.5 && < 5.0
  - bytestring
  - cassava
  - containers
  - free
  - lens
  - megaparsec
  - mtl
  - pipes
  - pipes-group
  - pipes-text
  - pretty-show
  - simple-amount
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src
  exposed-modules:
    - Journal.GainsKeeper
    - Journal.Parse
    - Journal.Pipes
    - Journal.Print
    - Journal.Split
    - Journal.ThinkOrSwim
    - Journal.Types
    - Journal.Utils
  dependencies:
    - data-default
    - pretty
    - profunctors
    - split
    - vector

tests:
  trade-journal-tests:
    main: Main.hs
    source-dirs: test
    dependencies:
      - HUnit
      - hedgehog
      - here
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - trade-journal

executables:
  trade-journal:
    main: Main.hs
    other-modules:
      - Options
    dependencies:
      - trade-journal
      - optparse-applicative
