name:        trade-journal
version:     0.0.3
license:     BSD3
author:      John Wiegley
maintainer:  johnw@newartisans.com
description: Command-line reporting utility for processing trade journals.

ghc-options:
   - -Wall
   - -Wno-missing-home-modules

dependencies:
  - aeson
  - base >= 4.5
  - bytestring
  - cassava
  - comonad
  - constraints
  - containers
  - data-default
  - free
  - lens
  - megaparsec
  - mtl
  - pretty
  - pretty-show
  - profunctors
  - row-types
  - semigroupoids
  - simple-amount >= 0.2.0
  - split
  - text
  - time
  - transformers
  - unordered-containers
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Trade.Journal.Types
    - Trade.Journal.Parse
    - Trade.Journal.Process
    - Trade.Journal.Zipper
    - Ledger
    - Ledger.Entry
    - Ledger.Render
    # - Trade.Closings
    # - Trade.Crypto.ICP
    # - Trade.Data.Zipper
    # - Trade.Journal.Entry
    # - Trade.Journal.Parse
    # - Trade.Journal.Pipes
    # - Trade.Journal.Print
    # - Trade.Journal.Split
    # - Trade.Journal.Types
    # - Trade.Journal.Utils
    # - Trade.Ledger
    # - Trade.Ledger.Entry
    # - Trade.Ledger.Render
    # - Trade.Process
    # - Trade.Provider.ThinkOrSwim
    - Trade.Provider.Coinmetro.Parser
    - Trade.Provider.Coinmetro.Process
    - Trade.Provider.Coinmetro.Types
    # - Trade.Taxes.USA.WashSaleRule
    # - Trade.Taxes.USA.WashSaleRule2

# tests:
#   journal-tests:
#     main: Main.hs
#     source-dirs: tests/Journal
#     dependencies:
#       - HUnit
#       - hedgehog
#       - here
#       - tasty
#       - tasty-hedgehog
#       - tasty-hunit
#       - trade-journal

#   thinkorswim-tests:
#     main: Main.hs
#     source-dirs: tests/Provider/ThinkOrSwim
#     dependencies:
#       - HUnit
#       - hedgehog
#       - here
#       - tasty
#       - tasty-hedgehog
#       - tasty-hunit
#       - trade-journal

#   coinmetro-tests:
#     main: Main.hs
#     source-dirs: tests/Provider/Coinmetro
#     dependencies:
#       - HUnit
#       - hedgehog
#       - here
#       - tasty
#       - tasty-hedgehog
#       - tasty-hunit
#       - trade-journal

executables:
  trade:
    main: Main.hs
    source-dirs: bin
    other-modules:
      - Options
    dependencies:
      - trade-journal
      - optparse-applicative
